# base image
FROM node:9.6.1

# set working directory
RUN mkdir /usr/src/app

ADD . /usr/src/app

WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
RUN npm i npm@latest -g

RUN yarn

# start app
CMD ["npm", "start"]