# Generated by Django 2.0.5 on 2018-08-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='eventhost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='eventlogistic',
            options={'ordering': ('date', 'start_time')},
        ),
        migrations.AlterModelOptions(
            name='officehost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='orghost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='orgtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sangguhost',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='event',
            name='outside_venue_name',
        ),
        migrations.AddField(
            model_name='eventlogistic',
            name='outside_venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='eventlogistic',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_events.Venue'),
        ),
        migrations.AlterField(
            model_name='officehost',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='orghost',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sangguhost',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
