# Generated by Django 2.0.5 on 2018-08-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_events', '0002_auto_20180822_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventhost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventlogistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='officehost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orghost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orgtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sangguhost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventlogistic',
            name='outside_venue_name',
        ),
        migrations.AddField(
            model_name='event',
            name='outside_venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventlogistic',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_events.Venue'),
        ),
    ]
