# Generated by Django 2.0.5 on 2018-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='abreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
