# Generated by Django 2.0.5 on 2018-06-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_events', '0002_auto_20180623_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='eventhost',
            name='host_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_events.HostType'),
        ),
    ]
