# Generated by Django 2.0.5 on 2018-06-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_events', '0003_auto_20180624_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhost',
            name='host_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_events.HostType'),
        ),
    ]
