version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/bash -c "sleep 5; python3 ls_ganap/manage.py runserver 0.0.0.0:8000"  
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db


      
