version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/bash -c "sleep 3; sh docker-entrypoint.sh"  
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db


      
